on:
  push:

jobs:
  docker:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        file: etc/packaging/32bit/Dockerfile
        tags: ghcr.io/viamrobotics/viam-server:armv7
        pull: true
        push: true
        platforms: linux/armv7
