on:
  push:

jobs:
  docker:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        file: etc/packaging/32bit/Dockerfile
        tags: ghcr.io/viamrobotics/viam-server:armv7
        pull: true
        push: true
        cache-from: type=registry,ref=ghcr.io/viamrobotics/viam-server:buildcache
        cache-to: type=registry,ref=ghcr.io/viamrobotics/viam-server:buildcache
        platforms: linux/armv7
  build:
    needs: [docker]
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    permissions:
      packages: read
    container:
      image: ghcr.io/viamrobotics/viam-server:armv7
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --platform linux/armv7
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: git config --global --add safe.directory '*'
    - name: test
      run: make test-go-no-race
    - name: build
      run: |
        go build -v -tags no_pigpio,no_tflite ./web/cmd/server
        file server
    - uses: actions/upload-artifact@v3
      with:
        path: server
  upload:
    needs: [build]
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
    - name: rename
      run: mv artifact/server viam-server-latest-armv7l
    - name: Authorize GCP Upload
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: upload
      uses: google-github-actions/upload-cloud-storage@v0.10.4
      with:
        headers: "cache-control: no-cache"
        path: viam-server-latest-armv7l
        destination: 'packages.viam.com/apps/viam-server/'
        parent: false
